language: java

matrix:
    include:
        - name: AdoptOpenJDK 11 on Windows
          os: windows
          language: shell
          install:
              - installJDK AdoptOpenJDK11
          env:
            - PATH=C:/Program Files/AdoptOpenJDK/jdk/bin:$PATH
            - JAVA_HOME=C:/Program Files/AdoptOpenJDK/jdk

script:
    - java -version
    - ./mvnw

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
