site_name: Hyperion
site_author: 'Thomas Lehmann <thomas.lehmann.private@gmail.com'
site_url: 'https://thomas-lehmann-private.github.io/hyperion/'
repo_url: 'https://github.com/thomas-lehmann-private/hyperion'

nav:
    - Home: index.md
    - Index:
       - hyperion.md
       - taskgroup.md
       - groovy.md
       - shell.md
       - docker-container.md
       - templating.md
       - matrix.md
       - Internal:
          - build.md
          - cli.md

theme:
    name: flatly

markdown_extensions:
