site_name: Hyperion
site_author: 'Thomas Lehmann <thomas.lehmann.private@gmail.com'
site_url: 'https://thomas-lehmann-private.github.io/hyperion/'
repo_url: 'https://github.com/thomas-lehmann-private/hyperion'

nav:
    - Home: index.md
    - User Guide:
       - hyperion.md
       - taskgroup.md
       - basic-coded-task-features.md
       - groovy.md
       - powershell.md
       - windows-batch.md
       - shell.md
       - docker-image.md
       - docker-container.md
       - templating.md
       - matrix.md
    - Developer Guide:
       - requirements.md
       - build.md
       - junit5.md
       - mkdocs.md
       - cli.md

theme:
    name: flatly

plugins:
  - search
  - mermaid2

markdown_extensions:
  - mkdocs_graphviz
  - admonition
  - footnotes
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.magiclink

